FROM openjdk:21
EXPOSE 8082
ADD ./target/api-be-student-enrollment-system-0.0.1-SNAPSHOT.jar api-be-student-enrollment-system-1.0.0.jar
ENTRYPOINT ["java", "-jar", "/api-be-student-enrollment-system-1.0.0.jar"]
