
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(2, 3, 'Finanzas');
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(3, 5, 'Matematica I');
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(4, 4, 'Economia');

INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(1, 23, 'Bart');
INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(2, 18, 'Liza');
INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(3, 44, 'Homero');

INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(1, 30, 'Lu,Ma 9-11am', 2);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(2, 30, 'Mi,Ju 4-6pm', 2);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(3, 30, 'Sa 2-6pm', 2);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(4, 2, 'Vi 8-11am', 3);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(5, 30, 'Mi,Vi 8-10am', 3);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID) VALUES(6, 30, 'Vi 8-11am', 4);



