-- Reset sequences
--ALTER SEQUENCE SEQ_DEPARTMENT RESTART WITH 1;
--ALTER SEQUENCE SEQ_COURSE RESTART WITH 1;
--ALTER SEQUENCE SEQ_INSTRUCTOR RESTART WITH 1;
--ALTER SEQUENCE SEQ_STUDENT RESTART WITH 1;
--ALTER SEQUENCE SEQ_SECTION RESTART WITH 1;
--ALTER SEQUENCE SEQ_ENROLLMENT RESTART WITH 1;
--ALTER SEQUENCE SEQ_ENROLLMENT_DETAIL RESTART WITH 1;

-- Departments (basic academic departments)
INSERT INTO TBL_DEPARTMENT (DEPARTMENT_ID, CODE, NAME, STATUS) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'CS', 'Computer Science', '1');
INSERT INTO TBL_DEPARTMENT (DEPARTMENT_ID, CODE, NAME, STATUS) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'MATH', 'Mathematics', '1');
INSERT INTO TBL_DEPARTMENT (DEPARTMENT_ID, CODE, NAME, STATUS) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'ENG', 'Engineering', '1');
INSERT INTO TBL_DEPARTMENT (DEPARTMENT_ID, CODE, NAME, STATUS) VALUES (SEQ_DEPARTMENT.NEXTVAL, 'PHY', 'Physics', '1');

-- Courses (with prerequisites and varying credits)
INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'CS101', 'Introduction to Programming', 'Basic programming concepts and algorithms', 4, 1, NULL, '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'CS102', 'Data Structures', 'Fundamental data structures and algorithms', 4, 1, 'CS101', '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'MATH101', 'Calculus I', 'Introduction to differential calculus', 4, 2, NULL, '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'MATH102', 'Calculus II', 'Introduction to integral calculus', 4, 2, 'MATH101', '1');

-- Cursos de Engineering
INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'ENG201', 'Introduction to Engineering', 'Fundamental concepts and principles of engineering design and problem solving', 4, 3, NULL, '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'ENG305', 'Materials Science', 'Study of materials properties, behavior, and applications in engineering', 3, 3, 'ENG201', '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'ENG410', 'Sustainable Engineering', 'Engineering principles and practices for sustainable development', 3, 3, 'ENG305', '1');

-- Cursos de Physics
INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'PHY101', 'General Physics I', 'Introduction to mechanics, thermodynamics, and waves', 4, 4, NULL, '1');

INSERT INTO TBL_COURSE (COURSE_ID, COURSE_CODE, NAME, DESCRIPTION, CREDITS, DEPARTMENT_ID, PREREQUISITES, STATUS) VALUES (SEQ_COURSE.NEXTVAL, 'PHY102', 'General Physics II', 'Introduction to electricity, magnetism, and optics', 4, 4, 'PHY101', '1');

-- Instructors (with different departments and degrees)
INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '12345678', 'John Smith', 'john.smith@university.edu', '987654321', 1, 'Ph.D. in Computer Science', TO_DATE('2020-01-15', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '23456789', 'Maria Garcia', 'maria.garcia@university.edu', '987654322', 2, 'Ph.D. in Mathematics', TO_DATE('2019-08-20', 'YYYY-MM-DD'), '1');

-- Instructores para Engineering y Physics
INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '45678901', 'Elena Rodriguez', 'elena.r@university.edu', '912345678', 3, 'PhD in Mechanical Engineering', TO_DATE('2018-08-15', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '45678902', 'Robert Chen', 'robert.c@university.edu', '912345679', 3, 'PhD in Civil Engineering', TO_DATE('2019-06-20', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '45678903', 'Maria Sanchez', 'maria.s@university.edu', '912345680', 4, 'PhD in Theoretical Physics', TO_DATE('2017-09-10', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, DNI, FULLNAME, EMAIL, PHONE_NUMBER, PRIMARY_DEPARTMENT_ID, ACADEMIC_DEGREE, HIRE_DATE, STATUS) VALUES (SEQ_INSTRUCTOR.NEXTVAL, '45678904', 'James Wilson', 'james.w@university.edu', '912345681', 4, 'PhD in Quantum Physics', TO_DATE('2020-01-15', 'YYYY-MM-DD'), '1');

-- Students (with different admission dates)
INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000001A', '87654321', 'Alice Johnson', 'alice.j@university.edu', '987654323', '123 Student St', TO_DATE('2000-05-15', 'YYYY-MM-DD'), 'F', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000002H', '87654322', 'Bob Wilson', 'bob.w@university.edu', '987654324', '456 Student St', TO_DATE('2001-07-20', 'YYYY-MM-DD'), 'M', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000003E', '87654323', 'Mark Thomson', 'mark.t@university.edu', '987654778', '999 Miami St', TO_DATE('2000-08-20', 'YYYY-MM-DD'), 'M', TO_DATE('2024-02-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000004K', '87654324', 'Sarah Martinez', 'sarah.m@university.edu', '987654325', '789 College Ave', TO_DATE('2001-03-12', 'YYYY-MM-DD'), 'F', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000005G', '87654325', 'David Chen', 'david.c@university.edu', '987654326', '321 University Blvd', TO_DATE('2000-11-30', 'YYYY-MM-DD'), 'M', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000006C', '87654326', 'Emily Brown', 'emily.b@university.edu', '987654327', '567 Academic Dr', TO_DATE('2001-09-25', 'YYYY-MM-DD'), 'F', TO_DATE('2024-02-15', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000007J', '87654327', 'Michael Rodriguez', 'michael.r@university.edu', '987654328', '890 Scholar Ln', TO_DATE('2000-07-14', 'YYYY-MM-DD'), 'M', TO_DATE('2024-02-15', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000008F', '87654328', 'Jessica Kim', 'jessica.k@university.edu', '987654329', '432 Education St', TO_DATE('2001-04-08', 'YYYY-MM-DD'), 'F', TO_DATE('2024-02-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000009B', '87654329', 'William Taylor', 'william.t@university.edu', '987654330', '765 Campus Rd', TO_DATE('2000-12-03', 'YYYY-MM-DD'), 'M', TO_DATE('2024-02-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000010K', '87654330', 'Sophia Garcia', 'sophia.g@university.edu', '987654331', '543 Research Ave', TO_DATE('2001-06-22', 'YYYY-MM-DD'), 'F', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000011G', '87654331', 'James Anderson', 'james.a@university.edu', '987654332', '876 Knowledge Way', TO_DATE('2000-10-17', 'YYYY-MM-DD'), 'M', TO_DATE('2024-03-01', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000012C', '87654332', 'Olivia Lee', 'olivia.l@university.edu', '987654333', '234 Science Park', TO_DATE('2001-02-28', 'YYYY-MM-DD'), 'F', TO_DATE('2024-02-15', 'YYYY-MM-DD'), '1');

INSERT INTO TBL_STUDENT (STUDENT_ID, STUDENT_CODE, DNI, FULLNAME, EMAIL, PHONE_NUMBER, ADDRESS, BIRTH_DATE, GENDER, ADMISSION_DATE, STATUS) VALUES (SEQ_STUDENT.NEXTVAL, '20000013J', '87654333', 'Daniel Nguyen', 'daniel.n@university.edu', '987654334', '654 Learning Ct', TO_DATE('2000-08-09', 'YYYY-MM-DD'), 'M', TO_DATE('2024-02-15', 'YYYY-MM-DD'), '1');

-- Sections (for the 2024-1 academic period)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 1, 'A', 1, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'MON-WED 09:00-11:00', 'LAB101', 30, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 3, 'A', 2, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'TUE-THU 09:00-11:00', 'B201', 35, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 3, 'B', 2, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'MON-WED 09:00-11:00', 'B201', 20, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 1, 'B', 1, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'TUE-THU 09:00-11:00', 'LAB101', 25, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 2, 'A', 2, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'SAT-SUN 09:00-11:00', 'B201', 20, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 4, 'A', 1, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'TUE-THU 12:00-14:00', 'LAB101', 25, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS) VALUES (SEQ_SECTION.NEXTVAL, 2, 'B', 1, '2024-1', TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'), 'TUE-THU 12:00-14:00', 'LAB101', 25, 0, '1');

-- Secciones para ENG201 (Introduction to Engineering)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG201'), 'A',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Elena Rodriguez'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'MON-WED 08:00-10:00', 'E101', 30, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG201'), 'B',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Robert Chen'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'MON-WED 14:00-16:00', 'E102', 30, 0, '1');

-- Secciones para ENG305 (Materials Science)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG305'), 'A',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Elena Rodriguez'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'TUE-THU 10:00-12:00', 'E201', 25, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG305'), 'B',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Robert Chen'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'TUE-THU 16:00-18:00', 'E202', 25, 0, '1');

-- Secciones para ENG410 (Sustainable Engineering)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG410'), 'A',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Elena Rodriguez'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'WED-FRI 08:00-10:00', 'E301', 20, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'ENG410'), 'B',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Robert Chen'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'WED-FRI 14:00-16:00', 'E302', 20, 0, '1');

-- Secciones para PHY101 (General Physics I)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'PHY101'), 'A',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Maria Sanchez'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'MON-WED 10:00-12:00', 'P101', 35, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'PHY101'), 'B',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'James Wilson'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'MON-WED 16:00-18:00', 'P102', 35, 0, '1');

-- Secciones para PHY102 (General Physics II)
INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'PHY102'), 'A',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'Maria Sanchez'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'TUE-THU 08:00-10:00', 'P201', 30, 0, '1');

INSERT INTO TBL_SECTION (SECTION_ID, COURSE_ID, SECTION_CODE, INSTRUCTOR_ID, ACADEMIC_PERIOD, START_DATE, END_DATE, SCHEDULE, ROOM_NUMBER, MAX_CAPACITY, ENROLLED_STUDENT_COUNT, STATUS)
VALUES (SEQ_SECTION.NEXTVAL, (SELECT COURSE_ID FROM TBL_COURSE WHERE COURSE_CODE = 'PHY102'), 'B',
        (SELECT INSTRUCTOR_ID FROM TBL_INSTRUCTOR WHERE FULLNAME = 'James Wilson'), '2024-1',
        TO_DATE('2024-03-15', 'YYYY-MM-DD'), TO_DATE('2024-07-15', 'YYYY-MM-DD'),
        'TUE-THU 14:00-16:00', 'P202', 30, 0, '1');


-- Enrollments (for 2024-1)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 1, '2024-1', 8, 2, 'Espero aprobar todos los cursos',  TO_TIMESTAMP('2024-03-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);


-- Enrollment Details
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 1, 1, 4, '1', NULL, NULL, 0, NULL, 'P');

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 1, 2, 4, '1', NULL, NULL, 0, NULL, 'P');

-- Update enrolled student count in sections
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = 1 WHERE SECTION_ID IN (1, 2);

-------------------------------------------


-- Matricula para el estudiante con ID 2 (Bob Wilson)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 2, '2024-1', 12, 3, 'Enfocado en ciencias básicas', TO_TIMESTAMP('2024-03-02 11:30:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Bob (3 cursos que no se cruzan en horario y sin prerrequisitos directos)
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 2, 1, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS101 Sección A (MON-WED 09:00-11:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 2, 2, 4, '1', NULL, NULL, 0, NULL, 'P'); -- MATH101 Sección A (TUE-THU 09:00-11:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 2, 15, 4, '1', NULL, NULL, 0, NULL, 'P'); -- PHY101 Sección B (MON-WED 16:00-18:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (1, 2, 15);


-- Matricula para el estudiante con ID 3 (Mark Thomson)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 3, '2024-1', 12, 3, 'Enfocado en cursos introductorios', TO_TIMESTAMP('2024-03-05 09:15:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Mark (sin prerrequisitos anidados)
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 3, 7, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS102 Sección B (TUE-THU 12:00-14:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 3, 2, 4, '1', NULL, NULL, 0, NULL, 'P'); -- MATH101 Sección A (TUE-THU 09:00-11:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 3, 15, 4, '1', NULL, NULL, 0, NULL, 'P'); -- PHY101 Sección B (MON-WED 16:00-18:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (7, 2, 15);


-- Matricula para el estudiante con ID 4 (Sarah Martinez)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 4, '2024-1', 12, 3, 'Enfocada en cursos de tarde', TO_TIMESTAMP('2024-03-10 16:45:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Sarah (sin prerrequisitos anidados)
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 4, 8, 4, '1', NULL, NULL, 0, NULL, 'P'); -- ENG201 Sección A (MON-WED 08:00-10:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 4, 16, 4, '1', NULL, NULL, 0, NULL, 'P'); -- PHY101 Sección A (TUE-THU 08:00-10:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 4, 6, 4, '1', NULL, NULL, 0, NULL, 'P'); -- MATH102 Sección A (TUE-THU 12:00-14:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (8, 16, 6);


-- Matrícula para el estudiante con ID 5 (David Chen)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 5, '2024-1', 8, 2, 'Cursos de ciencias básicas', TO_TIMESTAMP('2024-03-04 14:30:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para David (2 cursos sin cruce de horarios)
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 5, 1, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS101 Sección A (MON-WED 09:00-11:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 5, 6, 4, '1', NULL, NULL, 0, NULL, 'P'); -- MATH102 Sección A (TUE-THU 12:00-14:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (1, 6);


-- Matrícula para el estudiante con ID 6 (Emily Brown)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 6, '2024-1', 8, 2, 'Enfoque en física y matemáticas', TO_TIMESTAMP('2024-03-03 11:20:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Emily
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 6, 17, 4, '1', NULL, NULL, 0, NULL, 'P'); -- PHY102 Sección B (TUE-THU 14:00-16:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 6, 2, 4, '1', NULL, NULL, 0, NULL, 'P'); -- MATH101 Sección A (TUE-THU 09:00-11:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (17, 2);


-- Matrícula para el estudiante con ID 7 (Michael Rodriguez)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 7, '2024-1', 4, 1, 'Solo un curso este semestre', TO_TIMESTAMP('2024-03-07 09:45:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Michael
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 7, 4, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS101 Sección B (TUE-THU 09:00-11:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (4);


-- Matrícula para el estudiante con ID 8 (Jessica Kim)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 8, '2024-1', 8, 2, 'Cursos de ingeniería', TO_TIMESTAMP('2024-03-05 13:15:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para Jessica
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 8, 8, 4, '1', NULL, NULL, 0, NULL, 'P'); -- ENG201 Sección A (MON-WED 08:00-10:00)

INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 8, 5, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS102 Sección A (SAT-SUN 09:00-11:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (8, 10);


-- Matrícula para el estudiante con ID 9 (William Taylor)
INSERT INTO TBL_ENROLLMENT (ENROLLMENT_ID, STUDENT_ID, ACADEMIC_PERIOD, TOTAL_CREDITS, TOTAL_ENROLLED_COURSES, COMMENTS, ENROLLMENT_DATE, STATUS, TOTAL_CREDITS_EARNED, WEIGHTED_AVERAGE)
VALUES (SEQ_ENROLLMENT.NEXTVAL, 9, '2024-1', 4, 1, 'Curso de fin de semana', TO_TIMESTAMP('2024-03-08 16:30:00', 'YYYY-MM-DD HH24:MI:SS'), '1', 0, NULL);

-- Detalles de matrícula para William
INSERT INTO TBL_ENROLLMENT_DETAIL (ENROLLMENT_DETAIL_ID, ENROLLMENT_ID, SECTION_ID, CREDITS, STATUS, WITHDRAWAL_DATE, WITHDRAWAL_REASON, CREDITS_EARNED, FINAL_GRADE, GRADE_STATUS)
VALUES (SEQ_ENROLLMENT_DETAIL.NEXTVAL, 9, 5, 4, '1', NULL, NULL, 0, NULL, 'P'); -- CS102 Sección A (SAT-SUN 09:00-11:00)

-- Actualizar el contador de estudiantes matriculados
UPDATE TBL_SECTION SET ENROLLED_STUDENT_COUNT = ENROLLED_STUDENT_COUNT + 1 WHERE SECTION_ID IN (5);