
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(SEQ_COURSE.NEXTVAL, 3, 'Finanzas');
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(SEQ_COURSE.NEXTVAL, 5, 'Matematica I');
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(SEQ_COURSE.NEXTVAL, 4, 'Economia');
INSERT INTO TBL_COURSE (COURSE_ID, CREDITS, NAME) VALUES(SEQ_COURSE.NEXTVAL, 4, 'Quimica');

INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, NAME, DEPARTMENT) VALUES(SEQ_INSTRUCTOR.NEXTVAL, 'Ing. Julio Cesar', 'Finanzas');
INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, NAME, DEPARTMENT) VALUES(SEQ_INSTRUCTOR.NEXTVAL, 'Ing. Marco Aurelio', 'Matematica I');
INSERT INTO TBL_INSTRUCTOR (INSTRUCTOR_ID, NAME, DEPARTMENT) VALUES(SEQ_INSTRUCTOR.NEXTVAL, 'Ing. Flavio Sexto', 'Economia');

INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(SEQ_STUDENT.NEXTVAL, 23, 'Bart');
INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(SEQ_STUDENT.NEXTVAL, 18, 'Liza');
INSERT INTO TBL_STUDENT (STUDENT_ID, AGE, NAME) VALUES(SEQ_STUDENT.NEXTVAL, 44, 'Homero');

INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 30, 'Lu,Ma 9-11am', 2, 1);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 30, 'Mi,Ju 4-6pm', 2, 1);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 30, 'Sa 2-6pm', 2, 2);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 2, 'Vi 8-11am', 3, 2);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 30, 'Mi,Vi 8-10am', 3,  1);
INSERT INTO TBL_SECTION (SECTION_ID, MAXCAPACITY, SCHEDULE, COURSE_ID, INSTRUCTOR_ID) VALUES(SEQ_SECTION.NEXTVAL, 30, 'Vi 8-11am', 4, 3);



